In [1]:
import pandas as pd
data = pd.read_csv('data.txt', sep="\t", header = None, low_memory=False)
data

0         1         2         3        4         5        6        7    \
0       1 -0.004125  0.254095  0.001426 -0.01037 -0.538509  5.95534  1.04063   
1       1  0.031029  0.193761  0.012918 -0.00237  0.781415  5.18794  0.98963   
2       1  0.015678  0.182336 -0.003028 -0.02337  0.881194  5.66530  0.87563   
3       1  0.014525  0.176636 -0.006161 -0.02737  1.024900  6.10968  0.91063   
4       1  0.010349  0.179248 -0.008526 -0.02737  0.935697  5.83902  0.91063   
...   ...       ...       ...       ...      ...       ...      ...      ...   
4475   40 -0.015981  0.254373 -0.013341 -0.00101 -0.165105  5.15843  1.03999   
4476   40 -0.008857  0.238946 -0.010767 -0.00901 -0.034522  5.43013  1.01499   
4477   40  0.024672  0.213325  0.014418  0.01099  0.613841  4.55481  1.01499   
4478   40  0.025063  0.212210  0.015656  0.01299  0.593249  4.58374  0.95799   
4479   40  0.002555  0.232580 -0.004537 -0.00501  0.397291  4.82234  1.32099   

          8        9    ...      525           526       527      528  \
0    -1.37437 -0.10937  ...  1015.36  7.170320e+08  0.027384  2.53425   
1    -0.71937 -0.08737  ...  1015.78  7.058540e+08  0.016947  2.51513   
2    -0.71937 -0.08037  ...  1016.16  6.270180e+08  0.008129  2.25959   
3    -0.71937 -0.08037  ...  1015.61  5.597480e+08  0.007377  2.13924   
4    -0.75637 -0.08337  ...  1015.67  4.844730e+08  0.011448  1.93595   
...       ...      ...  ...      ...           ...       ...      ...   
4475 -1.19301 -0.15801  ...  1014.61  3.237410e+09  0.132094  9.48535   
4476 -1.10201 -0.14501  ...  1016.07  3.156070e+09  0.133406  8.73701   
4477 -0.57301 -0.10401  ...  1016.06  3.052520e+09  0.138525  8.90410   
4478 -0.64101 -0.10001  ...  1015.80  3.322710e+09  0.076570  8.97766   
4479 -0.98601 -0.13101  ...  1015.77  3.412910e+09  0.006876  9.20105   

          529       530      531        532        533  534  
0     17.3882   8.05589  1.80247  1413310.0  3028080.0    1  
1     16.5914   7.81769  1.52349  1390180.0  3016420.0    1  
2     15.2312   7.11684  1.25860  1234110.0  3004430.0    1  
3     14.4663   6.70236  1.26643  1102720.0  2992170.0    1  
4     12.5493   6.08647  1.22387   954322.0  2979610.0    1  
...       ...       ...      ...        ...        ...  ...  
4475  73.9901  31.82590  5.16972  6390410.0   398810.0    4  
4476  68.4041  29.83820  5.06743  6214830.0   412407.0    4  
4477  68.5051  30.45150  5.88492  6011070.0   425422.0    4  
4478  72.4431  30.38700  4.43563  6544010.0   439695.0    4  
4479  75.5608  30.77280  2.52386  6721730.0   454341.0    4  

[4480 rows x 535 columns]

In [2]:
header = pd.read_csv('labels.txt', sep="\n",header =None)
header

0
0                                 Subject index (1-40)
1                                    ECG_original_mean
2                                     ECG_original_std
3                              ECG_original_trimmean25
4                                  ECG_original_median
..                                                 ...
530            EDA_Functionals_power_Filt2geomean(abs)
531                EDA_Functionals_power_Filt2harmmean
532                     EDA_Functionals_power_Filt2mad
533                EDA_Functionals_power_Filt2baseline
534  Activity: 1-neutral, 2-emotional, 3-mental and...

[535 rows x 1 columns]

In [3]:
data[417][915] = 2000000
data[417] =pd.to_numeric(data[417])

<ipython-input-3-3536ead89d24>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[417][915] = 2000000


In [4]:
from sklearn.model_selection import train_test_split
x = data[[i for i in range(1,534)]]
y = data[534]
x_train, x_test, y_train, y_test = train_test_split(
x, y, test_size=0.33)

# Decission Tree

In [5]:
from sklearn import tree
clf1 = tree.DecisionTreeClassifier(criterion='entropy')
clf1.fit(x_train, y_train)
clf1.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'presort': 'deprecated',
 'random_state': None,
 'splitter': 'best'}

In [6]:
clf1.get_depth()

17

In [7]:
from sklearn import metrics
print(metrics.classification_report(y_train, clf1.predict(x_train)))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       748
           2       1.00      1.00      1.00       757
           3       1.00      1.00      1.00       744
           4       1.00      1.00      1.00       752

    accuracy                           1.00      3001
   macro avg       1.00      1.00      1.00      3001
weighted avg       1.00      1.00      1.00      3001



In [8]:
y_predict = clf1.predict(x_test)
print(metrics.classification_report(y_test, y_predict))
print(metrics.confusion_matrix(y_test, y_predict))

              precision    recall  f1-score   support

           1       0.96      0.94      0.95       372
           2       0.87      0.87      0.87       363
           3       0.86      0.85      0.85       376
           4       0.97      0.99      0.98       368

    accuracy                           0.91      1479
   macro avg       0.91      0.91      0.91      1479
weighted avg       0.91      0.91      0.91      1479

[[351   4  17   0]
 [  4 316  36   7]
 [ 11  43 319   3]
 [  1   0   1 366]]


# Random Forest

In [9]:
from sklearn.ensemble import RandomForestClassifier
clf2 = RandomForestClassifier(criterion='entropy')
clf2.fit(x_train, y_train)
clf2.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [10]:
print(metrics.classification_report(y_train, clf2.predict(x_train)))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       748
           2       1.00      1.00      1.00       757
           3       1.00      1.00      1.00       744
           4       1.00      1.00      1.00       752

    accuracy                           1.00      3001
   macro avg       1.00      1.00      1.00      3001
weighted avg       1.00      1.00      1.00      3001



In [11]:
y_predict = clf2.predict(x_test)
print(metrics.classification_report(y_test, y_predict))
print(metrics.confusion_matrix(y_test, y_predict))

              precision    recall  f1-score   support

           1       1.00      0.99      0.99       372
           2       0.98      0.99      0.98       363
           3       0.98      0.98      0.98       376
           4       1.00      1.00      1.00       368

    accuracy                           0.99      1479
   macro avg       0.99      0.99      0.99      1479
weighted avg       0.99      0.99      0.99      1479

[[368   0   4   0]
 [  0 360   3   0]
 [  0   9 367   0]
 [  0   0   0 368]]


# XGBoost

In [12]:
import xgboost as xgb
clf3 = xgb.XGBClassifier()
clf3.fit(x_train, y_train)
clf3.get_params()

c:\users\mini\appdata\local\programs\python\python38\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[08:52:09] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


{'objective': 'multi:softprob',
 'use_label_encoder': True,
 'base_score': 0.5,
 'booster': 'gbtree',
 'colsample_bylevel': 1,
 'colsample_bynode': 1,
 'colsample_bytree': 1,
 'enable_categorical': False,
 'gamma': 0,
 'gpu_id': -1,
 'importance_type': None,
 'interaction_constraints': '',
 'learning_rate': 0.300000012,
 'max_delta_step': 0,
 'max_depth': 6,
 'min_child_weight': 1,
 'missing': nan,
 'monotone_constraints': '()',
 'n_estimators': 100,
 'n_jobs': 8,
 'num_parallel_tree': 1,
 'predictor': 'auto',
 'random_state': 0,
 'reg_alpha': 0,
 'reg_lambda': 1,
 'scale_pos_weight': None,
 'subsample': 1,
 'tree_method': 'exact',
 'validate_parameters': 1,
 'verbosity': None}

In [13]:
print(metrics.classification_report(y_train, clf3.predict(x_train)))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       748
           2       1.00      1.00      1.00       757
           3       1.00      1.00      1.00       744
           4       1.00      1.00      1.00       752

    accuracy                           1.00      3001
   macro avg       1.00      1.00      1.00      3001
weighted avg       1.00      1.00      1.00      3001



In [14]:
y_predict = clf3.predict(x_test)
print(metrics.classification_report(y_test, y_predict))
print(metrics.confusion_matrix(y_test, y_predict))

              precision    recall  f1-score   support

           1       1.00      0.99      1.00       372
           2       0.99      0.99      0.99       363
           3       0.98      0.99      0.99       376
           4       1.00      1.00      1.00       368

    accuracy                           0.99      1479
   macro avg       0.99      0.99      0.99      1479
weighted avg       0.99      0.99      0.99      1479

[[370   0   2   0]
 [  0 358   4   1]
 [  0   3 373   0]
 [  0   0   0 368]]


# SVM

In [15]:
from sklearn import svm
clf4 = svm.SVC(C=10)
clf4.fit(x_train, y_train)
clf4.get_params()

{'C': 10,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'rbf',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [16]:
print(metrics.classification_report(y_train, clf4.predict(x_train)))

              precision    recall  f1-score   support

           1       0.32      0.82      0.46       748
           2       0.34      0.05      0.09       757
           3       0.42      0.09      0.14       744
           4       0.50      0.57      0.53       752

    accuracy                           0.38      3001
   macro avg       0.40      0.38      0.31      3001
weighted avg       0.40      0.38      0.31      3001



In [17]:
y_predict = clf4.predict(x_test)
print(metrics.classification_report(y_test, y_predict))
print(metrics.confusion_matrix(y_test, y_predict))

              precision    recall  f1-score   support

           1       0.32      0.81      0.46       372
           2       0.31      0.05      0.08       363
           3       0.36      0.07      0.12       376
           4       0.48      0.52      0.50       368

    accuracy                           0.36      1479
   macro avg       0.37      0.36      0.29      1479
weighted avg       0.37      0.36      0.29      1479

[[301   8  11  52]
 [255  17  17  74]
 [250  14  27  85]
 [140  16  19 193]]


# 5 Fold Cross Validation Results

In [18]:
from sklearn.model_selection import cross_validate, cross_val_predict
scoring = ['accuracy','recall_macro','precision_macro','f1_macro','recall_weighted','precision_weighted','f1_weighted']
scores = cross_validate(clf3, x_train, y_train, scoring=scoring, cv=5, return_estimator=True)
y_predict = cross_val_predict(clf3, x_train, y_train, cv=5)
print(metrics.confusion_matrix(y_train, y_predict))
scores

c:\users\mini\appdata\local\programs\python\python38\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[08:53:18] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[08:53:29] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[08:53:40] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[08:53:51] WARNING: C:/Users/Administrator/workspace/xgboost-win64_

c:\users\mini\appdata\local\programs\python\python38\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[08:54:15] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[08:54:26] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[08:54:39] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[08:54:50] WARNING: C:/Users/Administrator/workspace/xgboost-win64_

{'fit_time': array([11.23608565, 10.98093247, 10.8517642 , 11.84373498, 11.62969089]),
 'score_time': array([0.03291941, 0.03018832, 0.03020024, 0.03033829, 0.02982163]),
 'estimator': (XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
                colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
                gamma=0, gpu_id=-1, importance_type=None,
                interaction_constraints='', learning_rate=0.300000012,
                max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
                monotone_constraints='()', n_estimators=100, n_jobs=8,
                num_parallel_tree=1, objective='multi:softprob', predictor='auto',
                random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
                subsample=1, tree_method='exact', use_label_encoder=True,
                validate_parameters=1, verbosity=None),
  XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
                c

In [19]:
import numpy as np
for k in scores.keys():
    if k=='estimator':
        continue
    print(k)
    print(np.mean(scores[k]))
    print()

fit_time
11.308441638946533

score_time
0.030693578720092773

test_accuracy
0.9830027731558513

test_recall_macro
0.9829835115004638

test_precision_macro
0.9832222462418407

test_f1_macro
0.9830225731153739

test_recall_weighted
0.9830027731558513

test_precision_weighted
0.9832524804465852

test_f1_weighted
0.9830472746431346



In [20]:
clf = scores['estimator'][1]
clf.get_params()

{'objective': 'multi:softprob',
 'use_label_encoder': True,
 'base_score': 0.5,
 'booster': 'gbtree',
 'colsample_bylevel': 1,
 'colsample_bynode': 1,
 'colsample_bytree': 1,
 'enable_categorical': False,
 'gamma': 0,
 'gpu_id': -1,
 'importance_type': None,
 'interaction_constraints': '',
 'learning_rate': 0.300000012,
 'max_delta_step': 0,
 'max_depth': 6,
 'min_child_weight': 1,
 'missing': nan,
 'monotone_constraints': '()',
 'n_estimators': 100,
 'n_jobs': 8,
 'num_parallel_tree': 1,
 'predictor': 'auto',
 'random_state': 0,
 'reg_alpha': 0,
 'reg_lambda': 1,
 'scale_pos_weight': None,
 'subsample': 1,
 'tree_method': 'exact',
 'validate_parameters': 1,
 'verbosity': None}